%mySA_GUI_graphics Creates all the graphical objects of the GUI
%
% Syntax:  mySA_GUI_graphics()
%
% Inputs:
%
% Outputs:
%
%
% Example: 
%
% Other m-files required:
% Subfunctions: none
% MAT-files required: none
% MATLAB version: R2012b
%
% See also: 
%
% Authors: Giuliano Bernardi, Alexander Bertrand
% KU Leuven, Department of Electrical Engineering (ESAT/SCD)
% email: giuliano.bernardi@esat.kuleuven.be
% Website: http://homes.esat.kuleuven.be/~gbernard/index.html
% Created: 22-October-2013; Last revision: 20-October-2016

%------------- BEGIN CODE --------------
% Figure
S.fh = figure(100);
set(S.fh,'units','characters',...
              'position',[10 10 135 41],...
              'menubar','none',...
              'Color',[0.941176 0.941176 0.941176],...
              'name','Speech and Audio GUI',...
              'numbertitle','off',...
              'resize','off');
              
          
if ~verLessThan('matlab','8.4')          
    set(S.fh,'Renderer', 'painters');
end
          
% Menu          
S.mh_file = uimenu(S.fh,'Label','File');
S.eh_load = uimenu(S.mh_file,'Label','Load session');
S.eh_save = uimenu(S.mh_file,'Label','Save session');          
S.mh_help = uimenu(S.fh,'Label','Help');
S.eh_help = uimenu(S.mh_help,'Label','Help content');
S.eh_about = uimenu(S.mh_help,'Label','About','Separator','on');          


if ~verLessThan('matlab','8.4')
    % Dummy Axes to create legend (workaround with HG2)
    S.ax_l = axes( 'units','characters',...
                 'position',[28 9 17 5],...
                 'visible','off',...    
                 'XAxisLocation','bottom');               
    % Create a legend for the symbols (implemented drawing the symbols
    % and erasing them to leave the canvas blank)
    hold on;
    hdummy1 =  plot(0,0,'rx','Linewidth',S.mlw);
    hdummy2 =  plot(0,0,'ks','Linewidth',S.mlw);
    hdummy3 =  plot(0,0,'bo','Linewidth',S.mlw);
    S.lh      = legend('Audio','Noise','Mic.');
    set(S.lh,'units','characters','Fontsize',12)
end

% Axes
S.ax = axes( 'units','characters',...
             'Xlim',[0 S.rdim],...
             'Ylim',[0 S.rdim],...
             'OuterPosition', [-4.76 10.6769 75.4 25.2846],...
             'position',[10.5 19 50 20],...
             'GridLineStyle',':',...
             'XAxisLocation','bottom');   

         
if verLessThan('matlab','8.4')
    % Create a legend for the symbols (implemented drawing the symbols
    % and erasing them to leave the canvas blank)
    hold on;
    hdummy1 =  plot(0,0,'rx','Linewidth',3);
    hdummy2 =  plot(0,0,'ks','Linewidth',3);
    hdummy3 =  plot(0,0,'bo','Linewidth',3);
    lh      = legend('Audio','Noise','Mic.');
    posl = get(lh,'position');
    set(lh,'position',[26 9.5 ...
        posl(3)*0.85 posl(4)*0.85],'Fontsize',12)
    delete([hdummy1 hdummy2 hdummy3]);
end         
         
% Set grids and labels
grid on; grid minor;
xlabel 'x-dimension [m]'
ylabel 'y-dimension [m]'
         
% % Create a legend for the symbols (implemented drawing the symbols
% % and erasing them to leave the canvas blank)
% hold on;
% hdummy1 =  plot(0,0,'rx','Linewidth',1);
% hdummy2 =  plot(0,0,'ks','Linewidth',1);
% hdummy3 =  plot(0,0,'bo','Linewidth',1);
% S.lh      = legend('Audio','Noise','Mic.');
% S.posl = get(S.lh,'position');
% delete([hdummy1 hdummy2 hdummy3]);         
% set(S.lh,'units','characters','position',[35 11 S.posl(3)*0.85 S.posl(4)*0.85],'Fontsize',12)


% uibutton('units','characters',...
%          'BackgroundColor',[1 1 1],...
%          'position',[5 5 20 3],...
%          'Style','text',...
%          'String',{'$\Star$'},...
%          'Interpreter','latex')
% ---------------------------- COMPONENTS ---------------------------------
% ------------- PANEL
% Panel components
S.panel_comp = uipanel('unit','characters',...
                 'position',[70 15 30 25],...
                 'Title','Add component',...
                 'fontsize',8);
             
% ------------- BUTTONS
o1 = 10;
% Button Audio
S.pb_audio = uicontrol('style','push',...
                         'Enable','Off',...    
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[3 9.5+o1 10 3],...
                         'fontsize',10,...
                         'string','Audio');             
% Button Remove audio
S.pb_audio_rm = uicontrol('style','push',...
                         'Enable','On',...    
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[15 10+o1 6 2],...
                         'fontsize',10,...
                         'string','Del');                           
                     
% Button Noise
S.pb_noise = uicontrol('style','push',...
                         'Enable','Off',...    
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[3 5.5+o1 10 3],...
                         'fontsize',10,...
                         'string','Noise');    
                     
% Button Remove noise
S.pb_noise_rm = uicontrol('style','push',...
                         'Enable','On',...    
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[15 6+o1 6 2],...
                         'fontsize',10,...
                         'string','Del');                           

% Button Mic
S.pb_mic = uicontrol('style','push',...
                         'Enable','Off',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[3 1.5+o1 10 3],...
                         'fontsize',10,...
                         'string','Mic.');   

% Button Remove mic
S.pb_mic_rm = uicontrol('style','push',...
                         'Enable','On',...    
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[15 2+o1 6 2],...
                         'fontsize',10,...
                         'string','Del');                       
                     
                     
% ------------- TEXTBOXES
% Textbox Source             
S.text_audio = uicontrol('style','text',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[23 9+o1 5 3],...
                         'fontsize',12,...
                         'string','0');             
% Textbox Noise
S.text_noise = uicontrol('style','text',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[23 5+o1 5 3],...
                         'fontsize',12,...
                         'string','0');     

% Textbox Mic
S.text_mic = uicontrol('style','text',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[23 1+o1 5 3],...
                         'fontsize',12,...
                         'string','0');    
                     
% Textbox Number mics
S.text_nmics = uicontrol('style','text',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[3 -3.25+o1 10 3],...
                         'fontsize',10,...
                         'string','# mics');  

% Textbox Interdistance mics
S.text_dmics = uicontrol('style','text',...
                         'Parent',S.panel_comp,...
                         'units','characters',...
                         'position',[3 -5.25+o1 10 3],...
                         'fontsize',10,...
                         'string','d [cm]');    

% ------------- EDIT BOXES
% Editbox Number mics
S.ed_nmics = uicontrol('style','edit',...
                       'BackgroundColor',[1 1 1],...    
                       'Parent',S.panel_comp,...
                       'units','characters',...
                       'position',[15 -2+o1 10 2],...
                       'fontsize',12,...
                       'string','');                     
             
% Editbox Interdistance mics
S.ed_dmics = uicontrol('style','edit',...
                       'BackgroundColor',[1 1 1],...
                       'Parent',S.panel_comp,...
                       'units','characters',...
                       'position',[15 -4+o1 10 2],...
                       'fontsize',12,...
                       'string','');              
                   
% ---------------------------- BUTTON ---------------------------------
% Button reset components
S.pb_reset_cmp = uicontrol('style','push',...
                       'Parent',S.panel_comp,...    
                       'units','characters',...
                       'position',[2 1 25 3],...
                       'fontsize',10,...
                       'string','Reset Components');                    
                   
% ---------------------------- PARAMETERS ---------------------------------
% ------------- PANEL
% Panel Parameters
S.panel_par = uipanel('unit','characters',...
                 'position',[100 15 30 25],...
                 'Title','Parameters',...
                 'fontsize',8);
                                  
% ------------- TEXTBOXES
% Textbox Room dimension
S.text_rdim = uicontrol('style','text',...
                         'Parent',S.panel_par,...
                         'units','characters',...
                         'position',[3 10+o1 10 3],...
                         'fontsize',10,...
                         'string','Room dim. [m]');             
% Textbox Reverberation time
S.text_reverb = uicontrol('style','text',...
                         'Parent',S.panel_par,...
                         'units','characters',...
                         'position',[3 6+o1 10 3],...
                         'fontsize',10,...
                         'string','T60 [s]');     

% Textbox length RIR
S.text_lRIR = uicontrol('style','text',...
                         'Parent',S.panel_par,...
                         'units','characters',...
                         'position',[0 3+o1 15 3],...
                         'fontsize',10,...
                         'string','Length RIR [samples]');    
                     
% Textbox Fs
S.text_fs = uicontrol('style','text',...
                         'Parent',S.panel_par,...
                         'units','characters',...
                         'position',[2 -1+o1 10 3],...
                         'fontsize',10,...
                         'string','fs [kHz]');  

% ------------- EDIT BOXES
% Editbox Room dimension
S.ed_rdim = uicontrol('style','edit',...
                       'BackgroundColor',[1 1 1],...    
                       'Parent',S.panel_par,...
                       'units','characters',...
                       'position',[17 10.5+o1 10 2],...
                       'fontsize',12,...
                       'string',num2str(S.rdim));                     
             
% Editbox Reverberation time
S.ed_reverb = uicontrol('style','edit',...
                       'BackgroundColor',[1 1 1],...
                       'Parent',S.panel_par,...
                       'units','characters',...
                       'position',[17 7.25+o1 10 2],...
                       'fontsize',12,...
                       'string',num2str(S.reverb));   
                   

% ------------- POP UP MENUS                     
% Popup Fs
S.pp_fs = uicontrol('style','pop',...
                 'unit','characters',...
                 'Parent',S.panel_par,...
                 'position',[17 0.5+o1 10 2],...
                 'backgroundc',get(S.fh,'color'),...
                 'fontsize',10,'fontweight','bold',... 
                 'string',{'44.1';'16';'8'});

% Editbox length RIR
S.ed_lRIR = uicontrol('style','edit',...
                       'BackgroundColor',[1 1 1],...    
                       'Parent',S.panel_par,...
                       'units','characters',...
                       'position',[17 3.5+o1 10 2],...
                       'fontsize',12,...
                       'string',num2str(S.lRIR));                  
             
             
% ------------- BUTTON
% Button create RIRs
S.pb_create_RIRs = uicontrol('style','push',...
                           'Parent',S.panel_par,...
                           'units','characters',...
                           'position',[4 0.75 22 3.5],...
                           'fontsize',10,...
                           'string','Create/Store RIR');                
             

% ---------------------------- DOA-based trajectories ----------------------
% ------------- PANEL
% Panel draw DOA
S.panel_DOA = uipanel('unit','characters',...
                 'position',[70 1 60 14],...
                 'Title','Draw trajectories',...
                 'fontsize',8);   
o2 = 5;
% ------------- BUTTON
% Button Draw DOAs
S.pb_DOA = uicontrol('style','push',...
                           'Enable','Off',...
                           'Parent',S.panel_DOA,...
                           'units','characters',...
                           'position',[3 12.5-o2 15 3],...
                           'fontsize',10,...
                           'string','Draw',...
                           'tooltip','DOAs must be in degrees!');

% Button reset DOAs
S.pb_reset_DOA = uicontrol('style','push',...
                           'Enable','Off',...
                           'Parent',S.panel_DOA,...
                           'units','characters',...
                           'position',[3 8.5-o2 15 3],...
                           'fontsize',10,...
                           'string','Reset');

% ------------- TEXTBOX
% Textbox Room dimension
S.text_error_DOAs = uicontrol('style','text',...
                         'Parent',S.panel_DOA,...
                         'units','characters',...
                         'position',[29 10 20 2],...
                         'fontsize',10,...
                         'string','Errors [degrees]');    
                     
% ------------- LIST ERROR DOAS
% List Error doas
S.ls_error_DOAs = uicontrol('style','list',...
                            'Parent',S.panel_DOA,...
                         'units','characters',...
                         'BackgroundColor',[1 1 1],...    
                         'ForegroundColor',[0 0 0],...    
                         'position',[30 2 25 8],...
                         'fontsize',12,...
                         'Visible','on',...
                         'string','');                         


% ---------------------------- RESET ALL ---------------------------------
% Button reset all
S.pb_reset = uicontrol('style','push',...
                       'units','characters',...
                       'position',[24.25 1 20 3],...
                       'fontsize',10,...
                       'string','RESET ALL');

%------------- END CODE --------------                   